SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
    IF(B.STATUS = 'SALE', '판매중', IF (B.STATUS = 'RESERVED', '예약중', '거래완료'))
FROM USED_GOODS_BOARD AS B
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC