SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '세단' AND H.START_DATE LIKE '2022-10-%'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;